<?php
/**
 * LebanEASE Passenger Commit
 * Executes a Passenger-confirmed proposal (booking or cancellation)
 * atomically with re-validation to prevent race conditions.
 */

session_start();
require_once __DIR__ . '/user_agent_tools.php';

header('Content-Type: application/json; charset=utf-8');

function reply($data, int $status = 200): void {
    http_response_code($status);
    echo json_encode($data, JSON_UNESCAPED_UNICODE);
    exit;
}

$passenger_id = (int)($_SESSION['passenger_id'] ?? 0);
if ($passenger_id <= 0) {
    reply(['error' => 'You must be logged in to confirm this action'], 401);
}

$body     = json_decode(file_get_contents('php://input'), true) ?: [];
$proposal = $body['proposal'] ?? null;
if (!is_array($proposal)) {
    reply(['error' => 'No proposal provided'], 400);
}

$type = $proposal['type'] ?? '';
$pdo  = passenger_pdo();
$pdo->beginTransaction();

try {
    /* ====================================================================
       BOOKING
       ==================================================================== */
    if ($type === 'booking') {
        $sid  = (int)($proposal['schedule_id'] ?? 0);
        $seat = (int)($proposal['seat_number'] ?? 0);
        if ($sid <= 0 || $seat <= 0) {
            throw new RuntimeException('Invalid booking proposal');
        }

        // Re-validate: schedule exists & not cancelled
        $stmt = $pdo->prepare(
            "SELECT s.Schedule_ID, s.Status, s.Date, s.Departure_Time,
                    b.Capacity
             FROM Bus_Schedule s
             JOIN Bus b ON s.Bus_ID = b.Bus_ID
             WHERE s.Schedule_ID = :id"
        );
        $stmt->execute([':id' => $sid]);
        $sched = $stmt->fetch();
        if (!$sched) throw new RuntimeException('Schedule not found');
        if (strcasecmp($sched['Status'], 'Scheduled') !== 0) {
            throw new RuntimeException("This trip is no longer available (status: {$sched['Status']})");
        }
        if ($seat > (int)$sched['Capacity']) {
            throw new RuntimeException("Seat {$seat} exceeds Bus capacity");
        }

        // Re-validate seat free
        $stmt = $pdo->prepare(
            "SELECT COUNT(*) AS c FROM Reservation
             WHERE Schedule_ID = :sid AND Seat_Number = :seat
               AND Status NOT IN ('Cancelled','Refunded')"
        );
        $stmt->execute([':sid' => $sid, ':seat' => $seat]);
        $row = $stmt->fetch();
        if ((int)$row['c'] > 0) {
            throw new RuntimeException("Seat {$seat} was just booked by someone else. Please try a different seat.");
        }

        // Re-validate no duplicate booking by same Passenger on same schedule
        $stmt = $pdo->prepare(
            "SELECT COUNT(*) AS c FROM Reservation
             WHERE Schedule_ID = :sid AND Passenger_ID = :pid
               AND Status NOT IN ('Cancelled','Refunded')"
        );
        $stmt->execute([':sid' => $sid, ':pid' => $passenger_id]);
        $row = $stmt->fetch();
        if ((int)$row['c'] > 0) {
            throw new RuntimeException('You already have a Reservation on this trip');
        }

        // Insert only the real columns. Active_Seat_Number and Active_Passenger_ID
        // are generated by the database in database/LebanEase_updated.sql.
        $stmt = $pdo->prepare(
            "INSERT INTO Reservation
               (Seat_Number, Booking_Date, Status, Passenger_ID, Schedule_ID)
             VALUES (:seat, NOW(), 'Active', :pid, :sid)"
        );
        $stmt->execute([
            ':seat' => $seat,
            ':pid'  => $passenger_id,
            ':sid'  => $sid,
        ]);
        $new_id = (int)$pdo->lastInsertId();

        $pdo->commit();
        reply([
            'status'         => 'success',
            'action'         => 'booking',
            'reservation_id' => $new_id,
            'seat_number'    => $seat,
            'date'           => $sched['Date'],
            'departure_time' => $sched['Departure_Time'],
        ]);
    }

    /* ====================================================================
       CANCELLATION
       ==================================================================== */
    if ($type === 'cancellation') {
        $rid = (int)($proposal['reservation_id'] ?? 0);
        if ($rid <= 0) throw new RuntimeException('Invalid cancellation proposal');

        $stmt = $pdo->prepare(
            "SELECT Status FROM Reservation
             WHERE Reservation_ID = :rid AND Passenger_ID = :pid
             FOR UPDATE"
        );
        $stmt->execute([':rid' => $rid, ':pid' => $passenger_id]);
        $cur = $stmt->fetch();
        if (!$cur) throw new RuntimeException('Reservation not found or not yours');
        if (in_array(strtolower($cur['Status']), ['cancelled', 'refunded'], true)) {
            throw new RuntimeException('This Reservation is already cancelled');
        }

        // Only update Status. The generated active-* columns become NULL automatically.
        $stmt = $pdo->prepare(
            "UPDATE Reservation
             SET Status = 'Cancelled'
             WHERE Reservation_ID = :rid"
        );
        $stmt->execute([':rid' => $rid]);
        $pdo->commit();

        reply([
            'status'         => 'success',
            'action'         => 'cancellation',
            'reservation_id' => $rid,
        ]);
    }

    throw new RuntimeException("Unknown proposal type: {$type}");
} catch (Throwable $e) {
    if ($pdo->inTransaction()) $pdo->rollBack();
    reply(['error' => $e->getMessage()], 400);
}
